# Titanic_Naive_Bayes

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

In [6]:
from sklearn.naive_bayes import GaussianNB

In [20]:
df=pd.read_csv(r"G:\DATA-SCIENCE\titanicNB.csv")
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [21]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df

Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [24]:
inputs=df.drop('Survived',axis='columns')
inputs

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [27]:
target=df.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [28]:
dummies=pd.get_dummies(inputs.Sex)
dummies

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [29]:
inputs2=pd.concat([inputs,dummies],axis='columns')
inputs2

Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [31]:
inputs2.drop(['Sex','male'],axis='columns',inplace=True)
inputs2

Pclass   Age     Fare  female
0         3  22.0   7.2500       0
1         1  38.0  71.2833       1
2         3  26.0   7.9250       1
3         1  35.0  53.1000       1
4         3  35.0   8.0500       0
..      ...   ...      ...     ...
886       2  27.0  13.0000       0
887       1  19.0  30.0000       1
888       3   NaN  23.4500       1
889       1  26.0  30.0000       0
890       3  32.0   7.7500       0

[891 rows x 4 columns]

In [32]:
inputs2.columns[inputs2.isna().any()]

Index(['Age'], dtype='object')

In [36]:
mean=inputs2.Age.mean()
mean

29.69911764705882

In [38]:
inputs2.Age=inputs2.Age.fillna(mean)
inputs2

Pclass        Age     Fare  female
0         3  22.000000   7.2500       0
1         1  38.000000  71.2833       1
2         3  26.000000   7.9250       1
3         1  35.000000  53.1000       1
4         3  35.000000   8.0500       0
..      ...        ...      ...     ...
886       2  27.000000  13.0000       0
887       1  19.000000  30.0000       1
888       3  29.699118  23.4500       1
889       1  26.000000  30.0000       0
890       3  32.000000   7.7500       0

[891 rows x 4 columns]

In [51]:
X_train,X_test,y_train,y_test=train_test_split(inputs2,target,test_size=0.2)

In [52]:
model=GaussianNB()

In [53]:
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [54]:
model.score(X_test,y_test)

0.7821229050279329

In [57]:
model.predict(X_test)

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [58]:
model.predict_proba(X_test)

array([[7.79915710e-01, 2.20084290e-01],
       [9.20014381e-01, 7.99856190e-02],
       [2.26129293e-01, 7.73870707e-01],
       [9.62666961e-01, 3.73330391e-02],
       [5.51260994e-02, 9.44873901e-01],
       [3.55370727e-01, 6.44629273e-01],
       [8.93444745e-01, 1.06555255e-01],
       [2.22383190e-01, 7.77616810e-01],
       [9.61167524e-01, 3.88324758e-02],
       [9.62607753e-01, 3.73922467e-02],
       [6.72318601e-01, 3.27681399e-01],
       [3.94773689e-01, 6.05226311e-01],
       [1.72372554e-01, 8.27627446e-01],
       [9.56361553e-01, 4.36384468e-02],
       [9.63993918e-01, 3.60060815e-02],
       [9.64422217e-01, 3.55777829e-02],
       [9.20125981e-01, 7.98740188e-02],
       [9.20969201e-01, 7.90307992e-02],
       [9.25851486e-01, 7.41485137e-02],
       [9.62666961e-01, 3.73330391e-02],
       [9.52609152e-01, 4.73908479e-02],
       [9.56308728e-01, 4.36912717e-02],
       [9.61778785e-01, 3.82212146e-02],
       [2.17791810e-01, 7.82208190e-01],
       [9.626052

cross-validation

In [60]:
from sklearn.model_selection import cross_val_score
cross_val_score(model,X_train,y_train,cv=5)

array([0.76223776, 0.77622378, 0.79020979, 0.76056338, 0.80851064])